[package]
name = "server"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]

[dependencies]
tokio-core = { git = "https://github.com/tokio-rs/tokio-core" }
futures = "0.1.1"
log = "0.3.6"
env_logger = "0.3.5"
sha2 = "0.1.2"
